### ISSUE TITLE
有关随机句子优化问题

### ISSUE THREAD

**Issue by WhaleFell** [WhitemuTeam/Python-plan-list-maker#1]
## 不愧是大佬，那么自律。想起当年中考那个月还在玩游戏我........_忏悔ing_
**看了你的程序，感觉很实用，如果能出个GUI版本就更好了**
❎ 另，希望能优化一下添加自定义随机句子，将句子放在一个txt文件，可以读取并随机选择。
**😍大佬太牛逼啦😍**

**Comment by WhaleFell** [comment]
- [x] 改进后获取随机句子的代码，导入并运行random sen函数就可以获取句子，句子可以写入目录下的data.txt文件，以换行识别每一个句子。
```python
import random
import os

def random_sen():
    if not os.path.exists('data.txt'):
        print('data.txt不存在')
        with open('data.txt', 'w', encoding='utf8') as w:
            w.write('光是遇见，就很幸运～')
        return None
            
    with open('data.txt', 'r' , encoding='utf8') as f:
        datas = f.readlines()
        data  =  random.choice(datas)
    if data.strip() == '':
        random_sen()
    else:
        return data.strip()
        
if __name__ == '__main__':
        sen = random_sen()
        print(sen)
```

**Comment by Moemu** [comment]
感谢您的留言，您的提议现在已被提上鄙人日程
我现在已开始改写makingpro.py，届时makingpro.py支持GUI（基于PySimpleGUI），使用一言API获取句子，自定义句子（sen.txt）
后话:
其实鄙人的知识储备也没有像您所说的那么高，研究您相关的仓库后，我了解到对于Python的学习程度还确实比不上您

**Comment by Moemu** [comment]
尊敬的AdminWhaleFall：
您好。
关于您提到的问题与建议，我们通过2个小时的努力改编源代码并发布了3.0版本，您提议到的特性在3.0更新日志中有提及：[版本更新日志](https://github.com/WhitemuTeam/Python-plan-list-maker/releases/latest)
感谢您使用Python-plan-list-maker并联系WhitemuTeam并向我们提建议，如没有问题您可以关闭Issues
此敬
WhitemuTeam
